version: '3'
services:
  # services
  widget_market_rails:
    image: thegillis/widget_market_rails:latest
    depends_on:
      - postgres
    build:
      context: ./widget_market_rails
      args:
        BUNDLE_WITHOUT: ""
    volumes:
      - ./widget_market_rails:/usr/app
      - bundler:/bundle
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_USER: thegillis
      DB_PASS: thegillis

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: thegillis
      POSTGRES_PASSWORD: thegillis
      POSTGRES_DB: widget_market_development
    ports:
      - '5432:5432'
    volumes:
      - pgvolume:/var/lib/postgresql/data
volumes:
  bundler: {}
  pgvolume: {}

