# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1f42202c1ae1172a0fc8c830973e10faa90e5103a657a6fe98ea5027c3bd6a5f320de3ec96d8df2c4b4e18f08f0ee2b9349781a4d02bd5a248f25a7bba0fc71

test:
  secret_key_base: 4543adcaac3208134be0d49a9a00e256f4660b6bd4d0042a2b42ac5fcb3b37099e89e84fd05ff0e9fc4788997e7ca99c6baf172562369290402279bfa1214b85

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
